defaults:
  - filepaths: filepaths
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_cpu
  - _self_

rxn_file: known_reactions.parquet
rule_file: mechinformed_rules.csv
rxn_path: ${filepaths.processed_data}/pathway/${.rxn_file}
rule_path: ${filepaths.rules}/${.rule_file}
batch_size: 10000

hydra:
  run:
    dir: ${filepaths.interim_data}/pathway
  job:
    chdir: True
  sweep:
    dir: ${filepaths.interim_data}/pathway
    subdir: .