defaults:
  - filepaths: filepaths
  - _self_

src_file: mappings_sprhea_240310_v3_mapped_no_subunits_x_mechinformed_rules.parquet
input_path: ${filepaths.interim_data}/pathway/${.src_file}
resolver:
  _target_: enz_rxn_data.mapping.largest_subgraph

hydra:
  run:
    dir: ${filepaths.processed_data}/pathway
  job:
    chdir: True