defaults:
  - filepaths: filepaths
  - _self_

src_file: mappings_sprhea_240310_v3_mapped_no_subunits_x_imt_rules.parquet
input_path: ${filepaths.interim_data}/pathway/${.src_file}
resolver:
  _target_: enz_rxn_data.mapping.min_rule_resolver # largest_subgraph | min_rule_resolver

hydra:
  run:
    dir: ${filepaths.processed_data}/pathway
  job:
    chdir: True
  sweep:
    dir: ${filepaths.processed_data}/pathway
    subdir: .
  sweeper:
    params:
      src_file: mappings_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_98_rules.parquet,mappings_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_15_rules.parquet,mappings_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_6_rules.parquet,mappings_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_3_rules.parquet,mappings_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_2_rules.parquet